apiVersion: v1
kind: Pod
metadata:
  name: envoy-lab
spec:
  containers:
  - name: envoy
    image: docker.io/envoyproxy/envoy:v1.30.0
    ports:
    - containerPort: 10000
      name: http
    - containerPort: 9901
      name: admin
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]
    volumeMounts:
    - name: envoy-config-volume
      mountPath: /etc/envoy
  - name: python
    image: python:3
    command: ["/bin/sh", "-c", "sleep 3600"]
  volumes:
  - name: envoy-config-volume
    configMap:
      name: envoy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 10000 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    direct_response: { status: 200, body: { inline_string: "Hello World!" } }
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: some_service
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: some_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1234
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901